#!/bin/bash -fe

echo "-configs---------------------------------------"
echo "CMAKE_VERSION: ${CMAKE_VERSION}"
echo "MPICH_VERSION: $MPICH_VERSION"
echo "SZIP_VERSION: $SZIP_VERSION"
echo "HDF5_VERSION: $HDF5_VERSION"
echo "NETCDFC_VERSION: $NETCDFC_VERSION" 
echo "NETCDFCXX_VERSION: $NETCDFCXX_VERSION"
echo "NETCDFFORTRAN_VERSION: $NETCDFFORTRAN_VERSION"
echo "PNETCDF_VERSION: $PNETCDF_VERSION"
echo "-----------------------------------------------"

apt-get update
apt-get -y install software-properties-common
apt-get -y remove cmake
add-apt-repository universe
apt-get update && apt-get -y install locales csh cmake m4 libcurl4-openssl-dev libz-dev gcc g++ gfortran liblapack-dev make git wget subversion libxml2-utils libxml-libxml-perl libswitch-perl build-essential checkinstall zlib1g-dev libssl-dev python3-distutils

mkdir -p /usr/local/packages
mkdir -p /usr/local/sources
mkdir -p $HOME/projects/e3sm/cesm-inputdata

cd /usr/local/sources
wget --inet4-only https://github.com/Kitware/CMake/releases/download/v${CMAKE_VERSION}/cmake-${CMAKE_VERSION}.tar.gz
wget --inet4-only http://www.mpich.org/static/downloads/${MPICH_VERSION}/mpich-${MPICH_VERSION}.tar.gz
wget --inet4-only https://support.hdfgroup.org/ftp/lib-external/szip/${SZIP_VERSION}/src/szip-${SZIP_VERSION}.tar.gz
wget --inet4-only https://hdf-wordpress-1.s3.amazonaws.com/wp-content/uploads/manual/HDF5/HDF5_${HDF5_VERSION//./_}/source/hdf5-${HDF5_VERSION}.tar.gz
wget --inet4-only https://github.com/Unidata/netcdf-c/archive/v${NETCDFC_VERSION}.tar.gz
wget --inet4-only https://github.com/Unidata/netcdf-cxx4/archive/v${NETCDFCXX_VERSION}.tar.gz
wget --inet4-only https://github.com/Unidata/netcdf-fortran/archive/v${NETCDFFORTRAN_VERSION}.tar.gz
wget --inet4-only https://parallel-netcdf.github.io/Release/pnetcdf-${PNETCDF_VERSION}.tar.gz

# build cmake
tar xzf cmake-${CMAKE_VERSION}.tar.gz
cd cmake-${CMAKE_VERSION}
./configure --prefix=/usr/local/packages/cmake
make && make install
cd ..

# build mpich
tar xzf mpich-${MPICH_VERSION}.tar.gz
cd mpich-${MPICH_VERSION}
export CC=gcc
export CXX=g++
export FC=gfortran
./configure --prefix=/usr/local/packages/mpich
make && make install
cd ..

# build parallel szip
tar xzf szip-${SZIP_VERSION}.tar.gz
cd szip-${SZIP_VERSION}
export CC=/usr/local/packages/mpich/bin/mpicc
export CXX=/usr/local/packages/mpich/bin/mpicxx
export FC=/usr/local/packages/mpich\/bin/mpif90
./configure --prefix=/usr/local/packages/szip
make && make install
cd ..

# build serial hdf5
tar xzf hdf5-${HDF5_VERSION}.tar.gz
cd hdf5-${HDF5_VERSION}
export CC=gcc
export CXX=g++
export F77=gfortran
export FC=gfortran
./configure --prefix=/usr/local/packages/hdf5-serial --with-szlib=/usr/local/packages/szip --disable-parallel
make && make install
cd ..

# build parallel hdf5
rm -rf hdf5-${HDF5_VERSION}
tar xzf hdf5-${HDF5_VERSION}.tar.gz
cd hdf5-${HDF5_VERSION}
export CC=/usr/local/packages/mpich/bin/mpicc
export MPICC=/usr/local/packages/mpich/bin/mpicc
export CXX=/usr/local/packages/mpich/bin/mpicxx
export MPICXX=/usr/local/packages/mpich/bin/mpicxx
export FC=/usr/local/packages/mpich/bin/mpif90
export MPIF90=/usr/local/packages/mpich/bin/mpif90
export MPIFC=/usr/local/packages/mpich/bin/mpif90
./configure --prefix=/usr/local/packages/hdf5-parallel --with-szlib=/usr/local/packages/szip --enable-parallel
make && make install
cd ..

# build serial netcdf
tar xzf v${NETCDFC_VERSION}.tar.gz
cd netcdf-c-${NETCDFC_VERSION}
export CC=gcc
export MPICC=/usr/local/packages/mpich/bin/mpicc
export CXX=g++
export MPICXX=/usr/local/packages/mpich/bin/mpicxx
export F77=gfortran
export MPIF77=/usr/local/packages/mpich/bin/mpif77
export FC=gfortran
export MPIF90=/usr/local/packages/mpich/bin/mpif90
export MPIFC=/usr/local/packages/mpich/bin/mpif90
export CFLAGS='-I/usr/local/packages/hdf5-serial/include -I/usr/local/packages/szip/include'
export CXXFLAGS='-I/usr/local/packages/hdf5-serial/include -I/usr/local/packages/szip/include'
export LDFLAGS='-L/usr/local/packages/hdf5-serial/lib -L/usr/local/packages/szip/lib'
./configure --prefix=/usr/local/packages/netcdf-serial --disable-dap --enable-netcdf-4 --disable-shared --enable-static --with-hdf5=/usr/local/packages/hdf5-serial --with-szlib=/usr/local/packages/szip
make && make install
cd ..

tar xzf v${NETCDFCXX_VERSION}.tar.gz
cd netcdf-cxx4-${NETCDFCXX_VERSION}
export CC=gcc
export MPICC=/usr/local/packages/mpich/bin/mpicc
export CXX=g++
export MPICXX=/usr/local/packages/mpich/bin/mpicxx
export F77=gfortran
export MPIF77=/usr/local/packages/mpich/bin/mpif77
export FC=gfortran
export MPIF90=/usr/local/packages/mpich/bin/mpif90
export MPIFC=/usr/local/packages/mpich/bin/mpif90
export CFLAGS='-static -I/usr/local/packages/netcdf-serial/include -I/usr/local/packages/hdf5-serial/include -I/usr/local/packages/szip/include'
export CXXFLAGS='-static -I/usr/local/packages/netcdf-serial/include -I/usr/local/packages/hdf5-serial/include -I/usr/local/packages/szip/include'
export LDFLAGS='-L/usr/local/packages/netcdf-serial/lib -L/usr/local/packages/hdf5-serial/lib -L/usr/local/packages/szip/lib'
export LIBS='-lnetcdf -lhdf5_hl -lhdf5 -ldl -lsz -lm -lz'
./configure --prefix=/usr/local/packages/netcdf-serial --disable-dap --enable-netcdf-4 --disable-shared --enable-static --with-hdf5=/usr/local/packages/hdf5-serial --with-szlib=/usr/local/packages/szip
make && make install
cd ..

tar xzf v${NETCDFFORTRAN_VERSION}.tar.gz
cd netcdf-fortran-${NETCDFFORTRAN_VERSION}
export CC=gcc
export MPICC=/usr/local/packages/mpich/bin/mpicc
export CXX=g++
export MPICXX=/usr/local/packages/mpich/bin/mpicxx
export F77=gfortran
export MPIF77=/usr/local/packages/mpich/bin/mpif77
export FC=gfortran
export MPIF90=/usr/local/packages/mpich/bin/mpif90
export MPIFC=/usr/local/packages/mpich/bin/mpif90
export CFLAGS='-static -I/usr/local/packages/netcdf-serial/include -I/usr/local/packages/hdf5-serial/include -I/usr/local/packages/szip/include'
export CXXFLAGS='-static -I/usr/local/packages/netcdf-serial/include -I/usr/local/packages/hdf5-serial/include -I/usr/local/packages/szip/include'
export FFLAGS='-static -I/usr/local/packages/netcdf-serial/include -I/usr/local/packages/hdf5-serial/include -I/usr/local/packages/szip/include'
export FCFLAGS='-static -I/usr/local/packages/netcdf-serial/include -I/usr/local/packages/hdf5-serial/include -I/usr/local/packages/szip/include'
export LDFLAGS='-L/usr/local/packages/netcdf-serial/lib -L/usr/local/packages/hdf5-serial/lib -L/usr/local/packages/szip/lib'
export LIBS='-lnetcdf -lhdf5_hl -lhdf5 -ldl -lsz -lm -lz'
./configure --prefix=/usr/local/packages/netcdf-serial  --disable-dap --enable-netcdf-4 --disable-shared --enable-static --with-hdf5=/usr/local/packages/hdf5-serial --with-szlib=/usr/local/packages/szip --enable-valgrind-tests --enable-serial-tests --enable-extra-tests --enable-extra-example-tests
make && make install
cd ..

# build parallel netcdf
rm -rf netcdf-c-${NETCDFC_VERSION}
tar xzf v${NETCDFC_VERSION}.tar.gz
cd netcdf-c-${NETCDFC_VERSION}
export CC=/usr/local/packages/mpich/bin/mpicc
export MPICC=/usr/local/packages/mpich/bin/mpicc
export CXX=/usr/local/packages/mpich/bin/mpicxx
export MPICXX=/usr/local/packages/mpich/bin/mpicxx
unset F77
unset MPIF77
export FC=/usr/local/packages/mpich/bin/mpif90
export MPIF90=/usr/local/packages/mpich/bin/mpif90
export MPIFC=/usr/local/packages/mpich/bin/mpif90
export CFLAGS='-I/usr/local/packages/hdf5-parallel/include -I/usr/local/packages/szip/include'
export CXXFLAGS='-I/usr/local/packages/hdf5-parallel/include -I/usr/local/packages/szip/include'
unset FFLAGS
unset FCFLAGS
export LDFLAGS='-L/usr/local/packages/hdf5-parallel/lib -L/usr/local/packages/szip/lib'
unset LIBS
./configure --prefix=/usr/local/packages/netcdf-parallel --disable-dap --enable-netcdf-4 --disable-shared --enable-static --with-hdf5=/usr/local/packages/hdf5-parallel --with-szlib=/usr/local/packages/szip
make && make install
cd ..

rm -rf netcdf-cxx4-${NETCDFCXX_VERSION}
tar xzf v${NETCDFCXX_VERSION}.tar.gz
cd netcdf-cxx4-${NETCDFCXX_VERSION}
export CC=/usr/local/packages/mpich/bin/mpicc
export MPICC=/usr/local/packages/mpich/bin/mpicc
export CXX=/usr/local/packages/mpich/bin/mpicxx
export MPICXX=/usr/local/packages/mpich/bin/mpicxx
export FC=/usr/local/packages/mpich/bin/mpif90
export MPIF90=/usr/local/packages/mpich/bin/mpif90
export MPIFC=/usr/local/packages/mpich/bin/mpif90
export CFLAGS='-static -I/usr/local/packages/netcdf-parallel/include -I/usr/local/packages/hdf5-parallel/include -I/usr/local/packages/szip/include'
export CXXFLAGS='-static -I/usr/local/packages/netcdf-parallel/include -I/usr/local/packages/hdf5-parallel/include -I/usr/local/packages/szip/include'
export LDFLAGS='-L/usr/local/packages/netcdf-parallel/lib -L/usr/local/packages/hdf5-parallel/lib -L/usr/local/packages/szip/lib'
export LIBS='-lnetcdf -lhdf5_hl -lhdf5 -ldl -lsz -lm -lz'
./configure --prefix=/usr/local/packages/netcdf-parallel --disable-dap --enable-netcdf-4 --disable-shared --enable-static --with-hdf5=/usr/local/packages/hdf5-parallel --with-szlib=/usr/local/packages/szip
make && make install
cd ..

rm -rf netcdf-fortran-${NETCDFFORTRAN_VERSION}
tar xzf v${NETCDFFORTRAN_VERSION}.tar.gz 
cd netcdf-fortran-${NETCDFFORTRAN_VERSION}
export CC=/usr/local/packages/mpich/bin/mpicc
export MPICC=/usr/local/packages/mpich/bin/mpicc
export CXX=/usr/local/packages/mpich/bin/mpicxx
export MPICXX=/usr/local/packages/mpich/bin/mpicxx
export F77=/usr/local/packages/mpich/bin/mpif77
export MPIF77=/usr/local/packages/mpich/bin/mpif77
export FC=/usr/local/packages/mpich/bin/mpif90
export MPIF90=/usr/local/packages/mpich/bin/mpif90
export MPIFC=/usr/local/packages/mpich/bin/mpif90
export CFLAGS='-static -I/usr/local/packages/netcdf-parallel/include -I/usr/local/packages/hdf5-parallel/include -I/usr/local/packages/szip/include'
export CXXFLAGS='-static -I/usr/local/packages/netcdf-parallel/include -I/usr/local/packages/hdf5-parallel/include -I/usr/local/packages/szip/include'
export FFLAGS='-static -I/usr/local/packages/netcdf-parallel/include -I/usr/local/packages/hdf5-parallel/include -I/usr/local/packages/szip/include'
export FCFLAGS='-static -I/usr/local/packages/netcdf-parallel/include -I/usr/local/packages/hdf5-parallel/include -I/usr/local/packages/szip/include'
export LDFLAGS='-L/usr/local/packages/netcdf-parallel/lib -L/usr/local/packages/hdf5-parallel/lib -L/usr/local/packages/szip/lib'
export LIBS='-lnetcdf -lhdf5_hl -lhdf5 -ldl -lsz -lm -lz'
./configure --prefix=/usr/local/packages/netcdf-parallel  --disable-dap --enable-netcdf-4 --disable-shared --enable-static --with-hdf5=/usr/local/packages/hdf5-parallel --with-szlib=/usr/local/packages/szip --enable-valgrind-tests --enable-parallel-tests --enable-extra-tests --enable-extra-example-tests
make && make install
cd ..


# build pnetcdf
tar xzf pnetcdf-${PNETCDF_VERSION}.tar.gz
cd pnetcdf-${PNETCDF_VERSION}
export CC=/usr/local/packages/mpich/bin/mpicc
export MPICC=/usr/local/packages/mpich/bin/mpicc
export CXX=/usr/local/packages/mpich/bin/mpicxx
export MPICXX=/usr/local/packages/mpich/bin/mpicxx
unset F77
unset MPIF77
export FC=/usr/local/packages/mpich/bin/mpif90
export MPIF90=/usr/local/packages/mpich/bin/mpif90
export MPIFC=/usr/local/packages/mpich/bin/mpif90
unset CFLAGS
unset CXXFLAGS
unset FFLAGS
unset FCFLAGS
unset LDFLAGS
unset LIBS
./configure --prefix=/usr/local/packages/pnetcdf --disable-in-place-swap
make && make install

# remove the sources
cd ..
rm -rf /usr/local/sources
