name: blds

on:
  pull_request:
    branches: [ main ]
  push:
    branches: [ main ]
    tags:
      - 'v*'

env:
  SZIP_VERSION: "2.1.1"
  HDF5_VERSION: "1.10.6"
  NETCDFC_VERSION: "4.7.3"
  NETCDFCXX_VERSION: "4.3.1"
  NETCDFFORTRAN_VERSION: "4.4.4"
  PNETCDF_VERSION: "1.12.1"

jobs:
  ocis:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      id-token: write

    steps:
      - 
        name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: recursive
          show-progress: false
          persist-credentials: false
      -
        name: GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      -
        name: Meta
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: |
            ghcr.io/${{ github.repository }}
      - 
        name: QEMU
        uses: docker/setup-qemu-action@v3
      -
        name: Buildx
        uses: docker/setup-buildx-action@v3
      -
        name: Build
        uses: docker/build-push-action@v5
        with:
          context: .
          file: Dockerfile
          push: true
          tags: ghcr.io/${{ github.repository }}:test
          build-args: |
            SZIP_VERSION=${{ env.SZIP_VERSION }}
            HDF5_VERSION=${{ env.HDF5_VERSION }}
            NETCDFC_VERSION=${{ env.NETCDFC_VERSION }}
            NETCDFCXX_VERSION=${{ env.NETCDFCXX_VERSION }}
            NETCDFFORTRAN_VERSION=${{ env.NETCDFFORTRAN_VERSION }}
            PNETCDF_VERSION=${{ env.PNETCDF_VERSION }}
      -
        name: Test
        run: |
          docker run -v "${PWD}":/app/work ghcr.io/${{ github.repository }}:test ./e3sm-test
      -
        name: Push
        uses: docker/build-push-action@v5
        with:
          context: .
          file: Dockerfile
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          build-args: |
            SZIP_VERSION=${{ env.SZIP_VERSION }}
            HDF5_VERSION=${{ env.HDF5_VERSION }}
            NETCDFC_VERSION=${{ env.NETCDFC_VERSION }}
            NETCDFCXX_VERSION=${{ env.NETCDFCXX_VERSION }}
            NETCDFFORTRAN_VERSION=${{ env.NETCDFFORTRAN_VERSION }}
            PNETCDF_VERSION=${{ env.PNETCDF_VERSION }}
